version: "3"

services:
  mysql:
    image: registry.cn-guangzhou.aliyuncs.com/root-pandora/mysql:8.0
    restart: always
    env_file:
      - .env
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=qch@123456
      - MYSQL_USER=pandora
      - MYSQL_PASSWORD=qch@123456
      - MYSQL_DATABASE=pandora
    ports:
      - 3306:3306
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ${PATH_PREFIX}/mysql/data:/var/lib/mysql

  redis:
    image: registry.cn-guangzhou.aliyuncs.com/root-pandora/redis:6.2.17
    container_name: redis
    volumes:
      - ${PATH_PREFIX}/redis:/data
      - ./redis/conf.d:/etc/redis
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qch@123456
    ports:
      - "5432:5432"
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    volumes:
      - ${PATH_PREFIX}/postgres/data:/var/lib/postgresql/data
      - ./postgres/init.d:/docker-entrypoint-initdb.d

  rsshub:
    image: diygod/rsshub:latest
    restart: always
    ports:
      - '1200:1200'
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      CACHE_EXPIRE: 60
      REDIS_URL: 'redis://redis:6379/'
      BILIBILI_COOKIE: "buvid3=7F5AF70D-CA72-72E9-1580-0606570F4ADB74992infoc; b_nut=1763734774; _uuid=8154AF79-765A-297A-E1BA-E828D52819BE75433infoc; buvid_fp=8796ba34343f154a0bf462f02c174f26; buvid4=0EDFF33F-C291-C2AC-2E28-61168159AB8B75767-025112122-9UDtXO7d2L2Z6OH2QuSo9w%3D%3D; theme-tip-show=SHOWED; rpdid=|(Rllllm|Rl0J'u~YJ~)RRYk; theme-avatar-tip-show=SHOWED; hit-dyn-v2=1; LIVE_BUVID=AUTO3317643297275910; lang=zh-Hans; PVID=1; theme-switch-show=SHOWED; theme_style=light; DedeUserID=16294233; DedeUserID__ckMd5=7c407931d94a3f6d; CURRENT_LANGUAGE=; CURRENT_BLACKGAP=0; CURRENT_QUALITY=120; bsource=search_google; home_feed_column=5; browser_resolution=1456-897; bp_t_offset_16294233=1233747265789624320; CURRENT_FNVAL=4048; bili_ticket=eyJhbGciOiJIUzI1NiIsImtpZCI6InMwMyIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODY0MjczMzEsImlhdCI6MTc4NjE2ODA3MSwicGx0IjotMX0.7FyPdMcSiwSbk3OVvpgJ7usUpK8RGo7cXCZJSAEWx6Y; bili_ticket_expires=1786427271; SESSDATA=cbd803f2%2C1801875477%2C80f37%2A81CjAsI0htYGhoFe4eIjqoZil9mMX-_VdsfOUkJGQW2XUxuw25lG5-nPE-o0D13GufMwoSVkxTcWhjN19qbDdaLV90RWhnLXkzNGJCTHFOaE9BdHRoc1lZUVYyZm1ZXzRSSk84ZUpDY1d3eS11eWJobDRCNHRoQkEzMTFZWUk5bE5ta3g3UGx4a3RBIIEC; bili_jct=58a6bef977ed98e25c94f31fbfc76b14; sid=hivy02oa; b_lsid=BF91488C_19FE92F06D2"
      BILIBILI_COOKIE_1039576265: "buvid3=7F5AF70D-CA72-72E9-1580-0606570F4ADB74992infoc; b_nut=1763734774; _uuid=8154AF79-765A-297A-E1BA-E828D52819BE75433infoc; buvid_fp=8796ba34343f154a0bf462f02c174f26; buvid4=0EDFF33F-C291-C2AC-2E28-61168159AB8B75767-025112122-9UDtXO7d2L2Z6OH2QuSo9w%3D%3D; theme-tip-show=SHOWED; rpdid=|(Rllllm|Rl0J'u~YJ~)RRYk; theme-avatar-tip-show=SHOWED; hit-dyn-v2=1; LIVE_BUVID=AUTO3317643297275910; lang=zh-Hans; PVID=1; theme-switch-show=SHOWED; theme_style=light; DedeUserID=16294233; DedeUserID__ckMd5=7c407931d94a3f6d; CURRENT_LANGUAGE=; CURRENT_BLACKGAP=0; CURRENT_QUALITY=120; bsource=search_google; home_feed_column=5; browser_resolution=1456-897; bp_t_offset_16294233=1233747265789624320; CURRENT_FNVAL=4048; bili_ticket=eyJhbGciOiJIUzI1NiIsImtpZCI6InMwMyIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODY0MjczMzEsImlhdCI6MTc4NjE2ODA3MSwicGx0IjotMX0.7FyPdMcSiwSbk3OVvpgJ7usUpK8RGo7cXCZJSAEWx6Y; bili_ticket_expires=1786427271; SESSDATA=cbd803f2%2C1801875477%2C80f37%2A81CjAsI0htYGhoFe4eIjqoZil9mMX-_VdsfOUkJGQW2XUxuw25lG5-nPE-o0D13GufMwoSVkxTcWhjN19qbDdaLV90RWhnLXkzNGJCTHFOaE9BdHRoc1lZUVYyZm1ZXzRSSk84ZUpDY1d3eS11eWJobDRCNHRoQkEzMTFZWUk5bE5ta3g3UGx4a3RBIIEC; bili_jct=58a6bef977ed98e25c94f31fbfc76b14; sid=hivy02oa; b_lsid=BF91488C_19FE92F06D2"
      TWITTER_AUTH_TOKEN: "33617e96883a54d74dc45e4427b7335e0a323ff0"
      TWITTER_COOKIE: "auth_token=33617e96883a54d74dc45e4427b7335e0a323ff0"

    depends_on:
      - redis

  rss-feishu-bot:
    build: ./rss-feishu-bot
    container_name: rss-feishu-bot
    restart: always
    environment:
      FEISHU_WEBHOOK: "https://open.feishu.cn/open-apis/bot/v2/hook/51d4824e-6b5a-4d35-b3f6-3bc14ef4f0e8"
      BILI_RSS_URL: "http://rsshub:1200/bilibili/user/dynamic/1039576265"
      X_RSS_URL: "http://rsshub:1200/twitter/user/Sanchesssmith"
    volumes:
      - ./rss-feishu-bot/data:/data
    depends_on:
      - rsshub



