version: "3"

services:
  mysql:
    image: registry.cn-guangzhou.aliyuncs.com/root-pandora/mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - TZ=Asia/Shanghai
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./mysql/conf.d/:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    restart: always

  redis:
    image: registry.cn-guangzhou.aliyuncs.com/root-pandora/redis:6.2.17
    container_name: redis
    volumes:
      - ./redis/conf.d:/etc/redis
      - /data/redis:/data
    ports:
      - "6379:6379"
    restart: always



  elasticsearch:
    image: registry-vpc.cn-guangzhou.aliyuncs.com/kx-infra/elasticsearch:8.14.1
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - node.name=kx-infra-elasticsearch
      - ES_JAVA_OPTS=-Xms512m -Xmx1024m
      - xpack.security.enabled=false
      - discovery.type=single-node
      - TZ=Asia/Shanghai
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always


