version: "3"

services:
  mysql:
    image: registry.cn-guangzhou.aliyuncs.com/root-pandora/mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - TZ=Asia/Shanghai
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./mysql/conf.d/:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    restart: always

  redis:
    image: registry.cn-guangzhou.aliyuncs.com/root-pandora/redis:6.2.17
    container_name: redis
    volumes:
      - /data/redis:/data
      - ./redis/conf.d:/etc/redis
    ports:
      - "6379:6379"
    restart: always

  minio:
    image: registry.cn-guangzhou.aliyuncs.com/root-pandora/minio
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # Minio API端口
      - "9001:9001"  # Minio 控制台端口
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=qch@123456
    volumes:
      - /data/minio:/data  # 使用相对路径和数据卷
    networks:
      - minio-net

networks:
  minio-net:
    driver: bridge



