version: "3"

services:
  mysql:
    image: registry.cn-guangzhou.aliyuncs.com/root-pandora/mysql:8.0
    restart: always
    env_file:
      - .env
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=qch@123456
      - MYSQL_USER=pandora
      - MYSQL_PASSWORD=qch@123456
      - MYSQL_DATABASE=pandora
    ports:
      - 3306:3306
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ${PATH_PREFIX}/mysql/data:/var/lib/mysql

  redis:
    image: registry.cn-guangzhou.aliyuncs.com/root-pandora/redis:6.2.17
    container_name: redis
    volumes:
      - ${PATH_PREFIX}/redis:/data
      - ./redis/conf.d:/etc/redis
    ports:
      - "6379:6379"
    restart: always

  minio:
    image: registry.cn-guangzhou.aliyuncs.com/root-pandora/minio
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # Minio API端口
      - "9001:9001"  # Minio 控制台端口
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=qch@123456
    volumes:
      - ${PATH_PREFIX}/minio:/data  # 使用相对路径和数据卷
    networks:
      - minio-net

networks:
  minio-net:
    driver: bridge



